In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [4]:
df = pd.read_csv('suzuki_stock_data.csv')
df.head()

       Date       Close        High         Low        Open    Volume
0  1/5/2015  734.777649  747.170748  728.017776  745.634414   7380400
1  1/6/2015  707.943176  721.770191  707.021375  715.727274  11456000
2  1/7/2015  728.529968  732.319594  702.821966  705.587368  10361600
3  1/8/2015  750.448242  755.569358  733.650984  737.747876  10652000
4  1/9/2015  743.893433  757.413181  740.411073  755.672001  11038800

In [9]:
df['Date'] = pd.to_datetime(df['Date'])
df.index = df['Date']
df.drop('Date', axis = 1, inplace = True)

In [10]:
df['returns'] = df['Close'].pct_change()

In [11]:
df.head()

                 Close        High         Low        Open    Volume   returns
Date
2015-01-05  734.777649  747.170748  728.017776  745.634414   7380400       NaN
2015-01-06  707.943176  721.770191  707.021375  715.727274  11456000 -0.036521
2015-01-07  728.529968  732.319594  702.821966  705.587368  10361600  0.029080
2015-01-08  750.448242  755.569358  733.650984  737.747876  10652000  0.030086
2015-01-09  743.893433  757.413181  740.411073  755.672001  11038800 -0.008735

In [13]:
df = df.dropna(subset = ['returns'])

In [14]:
df.head()

                 Close        High         Low        Open    Volume   returns
Date
2015-01-06  707.943176  721.770191  707.021375  715.727274  11456000 -0.036521
2015-01-07  728.529968  732.319594  702.821966  705.587368  10361600  0.029080
2015-01-08  750.448242  755.569358  733.650984  737.747876  10652000  0.030086
2015-01-09  743.893433  757.413181  740.411073  755.672001  11038800 -0.008735
2015-01-13  739.796387  742.971478  724.740306  729.554155   4946800 -0.005508

In [65]:
X = df.drop('returns', axis = 1)
y = df['returns']

In [16]:
split = int(len(df)* 0.9)
X_train = X[:split]
X_test = X[split:]
y_train = y[:split]
y_test = y[split:]

In [17]:
model_rfr = RandomForestRegressor(n_estimators = 100, random_state = 42)
model_rfr.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [18]:
y_pred = model_rfr.predict(X_test)

In [20]:
r2_score = model_rfr.score(X_test, y_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

In [21]:
r2_score

-0.08655149076050628

In [22]:
mse

0.00046438847926853115

In [23]:
mae

0.01569360278622243

In [24]:
model_xg = XGBRegressor(n_estimators = 100, random_state = 42)
model_xg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [25]:
y_pred_xg = model_xg.predict(X_test)

In [26]:
r2_score = model_xg.score(X_test, y_test)
mse = mean_squared_error(y_test, y_pred_xg)
mae = mean_absolute_error(y_test, y_pred_xg)

In [27]:
r2_score

-0.17318312572959194

In [28]:
model_svr = SVR(kernel = 'rbf')
model_svr.fit(X_train, y_train)

SVR()

In [29]:
y_pred_svr = model_svr.predict(X_test)
r2_score = model_svr.score(X_test, y_test)
mse = mean_squared_error(y_test, y_pred_svr)
mae = mean_absolute_error(y_test, y_pred_svr)

In [30]:
r2_score

-1.0112765994880015

In [31]:
df['lag1'] = df['Close'].shift(1)
df['lag2'] = df['Close'].shift(2)
df['rolling_mean3']= df['Close'].rolling(window = 3).mean()

C:\Users\PREDATOR\AppData\Local\Temp\ipykernel_15684\341441256.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lag1'] = df['Close'].shift(1)
C:\Users\PREDATOR\AppData\Local\Temp\ipykernel_15684\341441256.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lag2'] = df['Close'].shift(2)
C:\Users\PREDATOR\AppData\Local\Temp\ipykernel_15684\341441256.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rolling_mean3']= df['Close'].rolling(window = 3).mean()

In [32]:
df.head()

                 Close        High  ...        lag2  rolling_mean3
Date                                ...
2015-01-06  707.943176  721.770191  ...         NaN            NaN
2015-01-07  728.529968  732.319594  ...         NaN            NaN
2015-01-08  750.448242  755.569358  ...  707.943176     728.973796
2015-01-09  743.893433  757.413181  ...  728.529968     740.957214
2015-01-13  739.796387  742.971478  ...  750.448242     744.712687

[5 rows x 9 columns]

In [34]:
df.dropna(subset = ['lag1', 'lag2', 'rolling_mean3'], inplace = True)

C:\Users\PREDATOR\AppData\Local\Temp\ipykernel_15684\297039260.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset = ['lag1', 'lag2', 'rolling_mean3'], inplace = True)

In [35]:
df.head()

                 Close        High  ...        lag2  rolling_mean3
Date                                ...
2015-01-08  750.448242  755.569358  ...  707.943176     728.973796
2015-01-09  743.893433  757.413181  ...  728.529968     740.957214
2015-01-13  739.796387  742.971478  ...  750.448242     744.712687
2015-01-14  725.047546  739.386670  ...  743.893433     736.245789
2015-01-15  757.822693  758.232382  ...  739.796387     740.888875

[5 rows x 9 columns]

In [36]:
X_new = df[['lag1', 'lag2', 'rolling_mean3']]
y_new = df['returns']

In [37]:
X_train_new = X_new[:split]
X_test_new = X_new[split:]
y_train_new = y_new[:split]
y_test_new = y_new[split:]

In [38]:
model_rfr.fit(X_train_new, y_train_new)

RandomForestRegressor(random_state=42)

In [40]:
r2_score = model_rfr.score(X_test_new, y_test_new)
print(r2_score)

0.13292485462592907

In [42]:
model = {
    'Random Forest Regressor': RandomForestRegressor(n_estimators = 100, random_state = 42),
    'XGBoost Regressor': XGBRegressor(n_estimators = 100, learning_rate = 0.1, max_depth = 6, random_state = 42),
    'Support Vector Regressor': SVR(kernel = 'rbf')
}
for key, model in model.items():
    model.fit(X_train_new, y_train_new)
    r2_score = model.score(X_test_new, y_test_new)
    print(f'{key} R2 Score: {r2_score}')

Random Forest Regressor R2 Score: 0.13292485462592907
XGBoost Regressor R2 Score: 0.1434077983453793
Support Vector Regressor R2 Score: -2.168066566140768

In [45]:
from sklearn.model_selection import TimeSeriesSplit, GridSearchCV

In [60]:
tscv = TimeSeriesSplit(n_splits = 5)

para_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 6, 9],
    'subsample': [0.8,1.0]
}
grid_search = GridSearchCV(estimator = XGBRegressor(random_state = 42), param_grid = para_grid, cv = tscv, scoring = 'r2', n_jobs = -1)

In [61]:
grid_search.fit(X_train_new, y_train_new)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 6, 9], 'n_estimators': [50, 100, 200],
                         'subsample': [0.8, 1.0]},
             scoring='r2')

In [62]:
grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}

In [64]:
grid_search.best_score_

np.float64(0.30910057246415523)

In [59]:
y_pred_gscv = grid_search.best_estimator_.predict(X_test_new)
r2_score = grid_search.best_estimator_.score(X_test_new, y_test_new)
print(f'Grid Search CV XGBoost R2 Score: {r2_score}')

Grid Search CV XGBoost R2 Score: 0.2029164484865309

In [57]:
y_pred_gscv

array([-1.3798992e-02,  7.3909047e-03,  1.0194517e-03, -7.6507139e-03,
       -2.7591686e-03,  6.7429417e-03,  8.6586699e-03, -2.0847386e-02,
       -1.5493234e-02, -6.7863981e-03,  1.1943353e-02, -1.3334005e-02,
        1.2485787e-02,  1.3466594e-02,  1.2447386e-03,  1.4565954e-02,
        6.4333077e-03, -1.4687780e-02, -4.3842797e-03,  1.5512220e-02,
       -1.4493505e-02, -3.2066241e-02, -1.8310988e-02, -4.3842797e-03,
       -3.9393236e-03, -5.0015403e-03, -1.9395333e-02, -2.0022886e-02,
       -1.0372171e-02, -7.9927463e-03,  1.7502608e-02,  6.0067992e-03,
        5.1320633e-03,  2.1892117e-02,  5.2182665e-03, -7.0586964e-03,
       -7.0586964e-03, -1.2798698e-02,  8.3337608e-04,  1.5851421e-02,
        1.2803740e-02,  9.0283528e-03,  6.6036950e-03,  1.1002893e-02,
        1.6601186e-02, -9.8568778e-03,  6.1233081e-03,  1.3912097e-02,
        4.2754053e-03,  1.1024798e-04,  9.6099740e-03, -3.5609026e-04,
       -8.0602262e-03,  8.4606279e-03,  2.5521971e-02, -9.9618817e-03,
        7.6114894e-03, -1.3323154e-02, -3.7289974e-03,  4.2754053e-03,
        1.7630475e-02,  6.3969460e-03,  1.0874754e-02, -4.0709693e-03,
       -3.8220580e-03, -1.4772799e-02, -6.2020319e-03, -1.5624807e-02,
        6.2502488e-03,  9.0283528e-03,  6.6036950e-03,  6.6036950e-03,
        6.6036950e-03,  6.6036950e-03,  6.6036950e-03,  6.6036950e-03,
        1.4176530e-02, -6.1179721e-04, -1.5624807e-02,  1.2335116e-02,
        6.6036950e-03,  1.4176530e-02, -6.1179721e-04,  2.1516940e-02,
       -1.2580682e-02, -2.3159213e-02, -5.3687464e-03, -7.0586964e-03,
       -7.0586964e-03, -7.0586964e-03,  2.2307517e-02,  3.4350410e-02,
       -1.9996271e-02,  1.7452095e-02, -7.0586964e-03, -7.0586964e-03,
       -7.0586964e-03,  2.2054451e-02, -4.0532113e-03,  9.9714176e-05,
        4.1083612e-02,  1.2321515e-02,  6.6036950e-03,  2.1237018e-02,
       -1.9996271e-02,  1.7452095e-02, -1.9996271e-02,  1.1002893e-02,
        9.0283528e-03,  1.4176530e-02, -6.1179721e-04, -1.2580682e-02,
        1.7786257e-02,  3.9157789e-02,  1.1081101e-02, -9.2088655e-03,
       -1.5493234e-02,  1.2759872e-02,  8.8116471e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.6280055e-03, -1.6280055e-03,
       -1.6280055e-03, -1.6280055e-03, -1.8310988e-02, -3.8220580e-03,
        8.3786417e-03,  1.2872087e-02, -1.4493505e-02, -1.4493505e-02],
      dtype=float32)